### ISSUE TITLE
兩種口罩皆售完的marker仍會出現在地圖上

### ISSUE THREAD

**Issue by bestian** [jedy05097952/The-F2E_Mask#1]
hi
我fork了你的repo測了一下
發現
"兩種口罩皆售完的marker仍會出現在地圖上"
不確定怎麼修改，通報一聲，謝謝 ~

**Comment by jedy05097952** [comment]
Hi ~
皆售完的 marker 會出現在地圖上是正常的
可以根據數量改成不同顏色的 marker 哦

不是 Bug 所以就先關掉了！
